### PR TITLE
Forward by f

### PR DESCRIPTION
**Pull request by roderik**
Made a bad branch, this also contains the MessageView commit. So merge this one after the previous one.

### CODE REVIEW

**Comment by nompute** [comment]
Hmm, I'm getting an invalid selector error when trying to use "f" to forward.  The message view navigation isn't working on 7.2 either (I think Mail 7 broke the old functionality).  Are you using 7.2 as well?  I'm going to take a closer look in the evening.

**Comment by roderik** [comment]
I'm on 7.2 as well. Using Xcode 5.1.
Forward does work in the list to the left, but not in the message view. Reply does in the message view.

I'm on a belgian azerty macbook air btw where cmd-shift-f is forward, maybe different on a qwerty macbook?

**Comment by nompute** [comment]
Hmm, Cmd+Shift+f is the "forward" shortcut, so it should be the same.  Still, could be related to keyboard settings.  I'll do some spelunking and get back to you.

**Comment by nompute** [comment]
Ah, found the problem.  In `overrideMessagesKeyDown`, in your case block for handling forwarding, you're calling out to `overrideMailKeyDown` instead.  There's some other odd behavior, though, like "reply-all" suddenly becoming only "reply", but I think I have other ways around that.  Why don't you fix the commit, and I'll go ahead and merge it first before making other changes.

**Comment by roderik** [comment]
Ok, seems to work fine now. I'm not seeing this wrong a/r behaviour

**Pull request merged**
