### PR TITLE
Fix intermitted archive keypress not working

### PR DESCRIPTION
**Pull request by roderik**

### CODE REVIEW

**Comment by nompute** [comment]
Hmm, interesting.  I haven't seen issues with the archiveMessages call failing intermittently - but I'm not ruling out the possibility.  Moving away from a selector to keycodes actually causes a different problem - keycodes are apparently different for each keyboard layout.  Your change, for example, breaks archiving on qwerty.

How frequently does archiving fail for you?  Are you using very rapid keypresses?  If I can reproduce it, maybe I can try to fix it while still using the selector.

**Comment by roderik** [comment]
It did not work in the message view. 

But ignore this for now, i realise my mistake. I used 14 aka "e" as key to press, and by chance this worked for me since i've mapped cmd-e to archive. I'll test if 0 (A) works as well for me on an azerty since it's in a different place, but i would think it would (http://web.archive.org/web/20100501161453/http://www.classicteck.com/rbarticles/mackeyboard.php)

**Comment by roderik** [comment]
ok, seems like it is a problem :) 0 on my keyboard is Q :)

**Comment by roderik** [comment]
- archive is ctrl-cmd-a, but since i remapped it to cmd-e there was some confusion. Fixed that
- the number in CGEventCreateKeyboardEvent is the physical place on the keyboard, so this commit is correct for me on an azerty, but not for anyone on a qwerty for example. Fixing this goes way beyond my non-existing objective-c skills.

I understand if this is not a priority for you, and my fork scratches my itch, so just close this pull request and if i find some nice titbit i think is useful for the main project i'll submit a separate pull request.

Thanks btw for this very useful tool :+1:

**Comment by nompute** [comment]
No problem :) If the issue is that it doesn't work in the message view, that's something I could look at fixing without necessarily changing the keymap.  I'm also an objc newbie, so working with Mail's reverse-engineered API is a lot of black magic.  Thanks for hacking on the project!

**Pull request closed without merging**
